---

- hosts: openvpn-server
  gather_facts: true
  become: true
  roles:
    - openvpn
    - easy-rsa
    - openvpn-server

- hosts: openvpn-client
  gather_facts: true
  become: true
  roles:
    - openvpn
    - openvpn-client
