---

- name: download easy-rsa
  get_url:
    url: "https://github.com/OpenVPN/easy-rsa/archive/{{ easyrsa_version }}.tar.gz"
    dest: "/tmp/easy-rsa-{{ easyrsa_version }}.tar.gz"
    checksum: sha256:a1fff75a27ea7da3f37fbfed715633f55b9ca25f5b14cac38e525c5c995e68ae
  register: easyrsa_download_result

- name: unarchive easy-rsa
  unarchive:
    src: "{{ easyrsa_download_result.dest }}"
    dest: /usr/local/src
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    remote_src: true

- name: copy easy-rsa
  command: cp -r "{{ easyrsa_src_dir }}/easyrsa3" "{{ openvpn_home }}"
  args:
    creates: "{{ easyrsa_home }}"
  become_user: "{{ openvpn_user }}"

- name: init pki
  command: ./easyrsa init-pki
  args:
    chdir: "{{ easyrsa_home }}"
    creates: "{{ easyrsa_pki_dir }}"
  become_user: "{{ openvpn_user }}"
