---

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: download python
  get_url:
    url: "{{ python_src_url }}"
    dest: "/tmp/Python-{{ python_version }}.tar.xz"
    checksum: "{{ python_src_checksum }}"
  register: python_download_result

- name: unarchive python
  unarchive:
    src: "{{ python_download_result.dest }}"
    dest: "{{ python_src_dir }}"
    remote_src: true

- name: configure
  command: ./configure --prefix={{ python_prefix }} --enable-shared --with-tcltk
  args:
    chdir: "{{ python_home }}"
    creates: "{{ python_home }}/Makefile"

- name: make
  command: make -j 4
  args:
    chdir: "{{ python_home }}"
    creates: "{{ python_home }}/python"

- name: make install
  command: make install -j 4
  args:
    chdir: "{{ python_home }}"
    creates: "{{ python_command }}"

- name: add path to libpython
  lineinfile:
    dest: /etc/ld.so.conf
    state: present
    line: '{{ python_prefix }}/lib'
  register: python_ld_conf_result

- name: ldconfig
  command: ldconfig
  when: python_ld_conf_result|changed

- name: add python version
  lineinfile:
    dest: '/usr/share/cmake/Modules/{{ item }}'
    state: present
    regexp: 'set\(_PYTHON3_VERSIONS [0-9\. ]*\)'
    line: 'set(_PYTHON3_VERSIONS 3.5 3.4 3.3 3.2 3.1 3.0)'
  with_items:
    - FindPythonInterp.cmake
    - FindPythonLibs.cmake

- name: pip install
  pip:
    state: present
    name: "{{ item }}"
    executable: "{{ python_prefix }}/bin/pip3"
  with_items: "{{ python_pip_packages }}"
