---

- name: copy config files
  template:
    src: server.conf
    dest: "{{ openvpn_home }}/server.conf"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: "0600"
  notify: restart openvpn

- name: create key
  command: |
    openssl req -new -newkey rsa:2048 -utf8 -batch -nodes \
      -out "{{ openvpn_server_csr_file }}" \
      -keyout "{{ openvpn_server_key_file }}"
  args:
    creates: "{{ openvpn_server_csr_file }}"
  become_user: "{{ openvpn_user }}"

- name: fetch csr
  fetch:
    src: "{{ openvpn_server_csr_file }}"
    dest: /tmp
  register: openvpn_server_csr_fetch_result

- name: sign csr
  command: |-
    openssl x509 -req -days 3650 -CAcreateserial \
      -extfile "{{ private_ca_home }}/server.ext" \
      -CA "{{ private_ca_crt_file }}" \
      -CAkey "{{ private_ca_key_file }}" \
      -passin "pass:PrivateCAPassword" \
      -in "{{ openvpn_server_csr_fetch_result.dest }}" \
      -out "{{ openvpn_server_csr_fetch_result.dest }}.crt"
  args:
    creates: "{{ openvpn_server_csr_fetch_result.dest }}.crt"
  delegate_to: localhost
  become: false

- name: copy crt
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: "0600"
  with_items:
    - src: "{{ openvpn_server_csr_fetch_result.dest }}.crt"
      dest: "{{ openvpn_server_crt_file }}"
    - src: "{{ private_ca_crt_file }}"
      dest: "{{ openvpn_home }}/ca.crt"

- name: generate Diffie Hellman parameter
  command: openssl dhparam -out "{{ openvpn_dhparam_file }}" 2048
  args:
    creates: "{{ openvpn_dhparam_file }}"
  become_user: "{{ openvpn_user }}"

# - name: generate ta.key
#   command: "{{ openvpn_prefix }}/sbin/openvpn --genkey --secret {{ openvpn_home }}/ta.key"
#   args:
#     chdir: "{{ openvpn_home }}"
#     creates: "{{ openvpn_home }}/ta.key"
#   become_user: "{{ openvpn_user }}"
